import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/common/styles/globals.scss";
import "swiper/css";
import "swiper/css/navigation";
import "swiper/css/pagination";
import { ReduxProviders } from "@/common/redux/provider";
import Providers from "@/common/utils/provider";
import Script from "next/script";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <head>
                <link
                    href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css"
                    rel="stylesheet"
                />
                <link
                    href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css"
                    rel="stylesheet"
                />
                <link
                    href="/lib/owl-carousel/assets/owl.carousel.min.css"
                    rel="stylesheet"
                />
                <link
                    href="/lib/light-box/css/lightbox.min.css"
                    rel="stylesheet"
                />
                <link href="/lib/animate/animate.min.css" rel="stylesheet" />

                <link href="/css/bootstrap.min.css" rel="stylesheet" />

                <link href="/css/style.css" rel="stylesheet" />
                <Script src="https://code.jquery.com/jquery-3.4.1.min.js"></Script>
                <Script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"></Script>
                <Script src="/lib/wow/wow.min.js"></Script>
                <Script src="/lib/typed/typed.min.js"></Script>
                <Script src="/lib/easing/easing.min.js"></Script>
                <Script src="/lib/waypoints/waypoints.min.js"></Script>
                <Script src="/lib/counterup/counterup.min.js"></Script>
                <Script src="/lib/owlcarousel/owl.carousel.min.js"></Script>
                <Script src="/lib/isotope/isotope.pkgd.min.js"></Script>
                <Script src="/lib/lightbox/js/lightbox.min.js"></Script>

                <Script src="/js/main.js"></Script>
            </head>
            <body className={inter.className}>
                <ReduxProviders>
                    <Providers>{children}</Providers>
                </ReduxProviders>
            </body>
        </html>
    );
}
