export const QUERY_KEYS = Object.freeze({
  LIST_BLOG_TV: "LIST_BLOG_TV",
  LIST_TIN_TD_TV:"LIST_TIN_TD_TV",
  LIST_TIN_UV_TV: "LIST_TIN_UV_TV",
  LIST_BLOG_WORK: "LIST_BLOG_WORK",
  LIST_TIN_TD_WORK:"LIST_TIN_TD_WORK",
  LIST_TIN_UV_WORK: "LIST_TIN_UV_WORK",
  LIST_VIDEO: "LIST_VIDEO",
  LIST_NOTI: "LIST_NOTI",
  GET_DATA_CV:"GET_DATA_CV"
});
